# Generated by Django 2.2.1 on 2019-10-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(null=True, to='course.Course'),
        ),
    ]
